#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:30:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output d2q9-bgk.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`


# mpirun -np 2 -l ./d2q9-bgk input_128x256.params obstacles_128x256.dat

#! Run the executable
for i in {1..112}
do
    # mpirun -np $i -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat
    # mpirun -np $i -l ./d2q9-bgk input_128x256.params obstacles_128x256.dat
    # mpirun -np $i -l ./d2q9-bgk input_256x256.params obstacles_256x256.dat
    mpirun -np $i -l ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
done

# mpirun -np 5 -l ./d2q9-bgk input_8x8.params obstacles_8x8.dat
# mpirun -np 112 -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpirun -np 112 -l ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# mpirun -np 112 -l ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# mpirun -np 112 -l ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

#! Generate roofline data
# advixe-cl --collect=roofline --project-dir=./advi_results1 -- ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# advixe-cl --collect=roofline --project-dir=./advi_results2 -- ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# advixe-cl --collect=roofline --project-dir=./advi_results3 -- ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
# advixe-cl --collect=roofline --flop --project-dir=./advi_results4 -- mpiexec -n 112 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# advixe-cl --collect=roofline --flop --project-dir=./advi_results5 -- mpiexec -n 112 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# advixe-cl --collect=roofline --flop --project-dir=./advi_results6 -- mpiexec -n 112 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# advixe-cl -collect roofline -r ./advi_results_4 -- mpirun -np 112 -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat

# mpiexec -genvall -n 112 -ppn 112 -gtool "advixe-cl --collect=survey --project-dir=advi_results_4/project1:0-111" ./d2q9-bgk input_128x128.params obstacles_128x128.dat

# mpiexec -genvall -n 112 -ppn 112 -gtool "advixe-cl --collect=tripcounts --flop --project-dir=advi_results_4/project1:0-111" ./d2q9-bgk input_128x128.params obstacles_128x128.dat
